#!/bin/bash
sudo pacman -S haveged
sudo systemctl enable haveged
sudo systemctl start haveged
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syy
sudo pacman -S lxdm xdg-utils gtk-engine-aurora gnome-keyring gnome-disk-utility cantarell-fonts polkit-gnome networkmanager networkmanager-dispatcher-ntpd network-manager-applet ntp numix-themes xfce4 xfce4-screenshooter xfce4-clipman-plugin xfce4-taskmanager dosfstools ntfs-3g ristretto gamin leafpad lynx gvfs gnome-themes-standard thunar-archive-plugin ttf-liberation firefox xdg-user-dirs p7zip unzip zip unrar gtk-engine-murrine wget xfce4-whiskermenu-plugin xfce4-notifyd youtube-dl --noconfirm
xdg-user-dirs-update
sudo mv /etc/lxdm/lxdm.conf /etc/lxdm/lxdm.conf.back
sudo cp arch_xfce/lxdm.conf /etc/lxdm/lxdm.conf
chmod +x arch_xfce/aur_ins
sudo updatedb
chmod +x arch_xfce/post-clean
arch_xfce/post-clean
sudo systemctl enable lxdm
sudo systemctl enable ntpd
sudo systemctl enable NetworkManager
rm -r ~/.mozilla
rm -r ~/.config
rm -r ~/.local
cp -r arch_xfce/.config ~/.config
cp -r arch_xfce/.local ~/.local
cp -r arch_xfce/.mozilla ~/.mozilla
cp arch_xfce/.gtkrc-2.0 ~/.gtkrc-2.0
cp arch_xfce/.bashrc ~/.bashrc
arch_xfce/aur_ins
