#!/bin/bash
sudo pacman -S haveged
sudo systemctl enable haveged
sudo systemctl start haveged
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syy
sudo pacman -S lxdm faenza-icon-theme gtk-engine-aurora gnome-keyring gnome-disk-utility cantarell-fonts polkit-gnome networkmanager networkmanager-dispatcher-ntpd network-manager-applet ntp numix-themes xfce4 xfce4-screenshooter xfce4-clipman-plugin xfce4-taskmanager dosfstools ntfs-3g ristretto gamin leafpad lynx gvfs gnome-themes-standard thunar-archive-plugin firefox flashplugin xdg-user-dirs p7zip unzip zip unrar gtk-engine-murrine synapse wget xfce4-whiskermenu-plugin xfce4-notifyd youtube-dl --noconfirm
xdg-user-dirs-update
chmod +x arch_xfce/aur_ins
sudo updatedb
sudo systemctl enable lxdm
sudo systemctl enable ntpd
sudo systemctl enable NetworkManager
rm -r ~/.config
rm -r ~/.local
cp -r arch_xfce/.config ~/.config
cp -r arch_xfce/.local ~/.local
cp arch_xfce/.gtkrc-20 ~/.gtkrc-20
cp arch_xfce/.bashrc ~/.bashrc
