#!/bin/bash
sudo gtk-update-icon-cache /usr/share/icons/Faenza
sudo gtk-update-icon-cache /usr/share/icons/Faenza-Dark
sudo gtk-update-icon-cache /usr/share/icons/Faenza-Darkest
sudo gtk-update-icon-cache /usr/share/icons/Faenza-Darker
sudo gtk-update-icon-cache /usr/share/icons/Faenza-Ambiance
sudo gtk-update-icon-cache /usr/share/icons/Faenza-Radiance
sudo gtk-update-icon-cache /usr/share/icons/HighContrast
sudo gtk-update-icon-cache /usr/share/icons/hicolor
